### ISSUE TITLE
joborun linux

### ISSUE THREAD

**Issue by fungilife** [firasuke/awesome#4]
Arch like built from core build tools, maintains arch compatibility, no systemd no elogind - runit and/or s6 and 66, started 2021 daily maintained to be on par with arch-testing  https://joborun.neocities.org/joborun source: https://git.disroot.org/joborun-pkg support: https://diaspora-fr.org/tags/joborun (archive https://www.reddit.com/r/joborun/) 

Superboxon.com finally decided to call it quits, site up till next month

There is also a resurrected project from the distant past called DSL (damn small linux) based on antiX and using runit https://www.damnsmalllinux.org/

**Comment by firasuke** [comment]
Both projects were added. Thanks for bringing them again to my attention!
